apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: datum
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: datum
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: datum
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        # Projects are configured by default to adhere to the "restricted" Pod Security Standards.
        # This ensures that deployments meet the highest security requirements for Kubernetes.
        # For more details, see: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - args:
          - controller-manager
          - --metrics-bind-address=$(METRICS_BIND_ADDRESS)
          - --health-probe-bind-address=$(HEALTH_PROBE_BIND_ADDRESS)
          - --leader-elect=$(LEADER_ELECT)
          - --leader-election-id=$(LEADER_ELECTION_ID)
          - --leader-election-namespace=$(LEADER_ELECTION_NAMESPACE)
          - --leader-election-lease-duration=$(LEADER_ELECTION_LEASE_DURATION)
          - --leader-election-renew-deadline=$(LEADER_ELECTION_RENEW_DEADLINE)
          - --leader-election-retry-period=$(LEADER_ELECTION_RETRY_PERIOD)
          - --leader-election-release-on-cancel=$(LEADER_ELECTION_RELEASE_ON_CANCEL)
          - --metrics-secure=$(METRICS_SECURE)
          - --webhook-cert-path=$(WEBHOOK_CERT_PATH)
          - --webhook-cert-name=$(WEBHOOK_CERT_NAME)
          - --webhook-cert-key=$(WEBHOOK_CERT_KEY)
          - --metrics-cert-path=$(METRICS_CERT_PATH)
          - --metrics-cert-name=$(METRICS_CERT_NAME)
          - --metrics-cert-key=$(METRICS_CERT_KEY)
          - --enable-http2=$(ENABLE_HTTP2)
          - --config=$(CONFIG_FILE)
        env:
          - name: METRICS_BIND_ADDRESS
            value: "0"
          - name: HEALTH_PROBE_BIND_ADDRESS
            value: ":8081"
          - name: LEADER_ELECT
            value: "true"
          - name: LEADER_ELECTION_ID
            value: "81afa9db.datumapis.com"
          - name: LEADER_ELECTION_NAMESPACE
            value: ""
          - name: LEADER_ELECTION_LEASE_DURATION
            value: "15s"
          - name: LEADER_ELECTION_RENEW_DEADLINE
            value: "10s"
          - name: LEADER_ELECTION_RETRY_PERIOD
            value: "2s"
          - name: LEADER_ELECTION_RELEASE_ON_CANCEL
            value: "false"
          - name: METRICS_SECURE
            value: "true"
          - name: WEBHOOK_CERT_PATH
            value: ""
          - name: WEBHOOK_CERT_NAME
            value: "tls.crt"
          - name: WEBHOOK_CERT_KEY
            value: "tls.key"
          - name: METRICS_CERT_PATH
            value: ""
          - name: METRICS_CERT_NAME
            value: "tls.crt"
          - name: METRICS_CERT_KEY
            value: "tls.key"
          - name: ENABLE_HTTP2
            value: "false"
          - name: CONFIG_FILE
            value: ""
        image: ghcr.io/datum-cloud/datum:latest
        name: datum-controller-manager
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
