apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: owner
  annotations:
    kubernetes.io/display-name: Owner
    kubernetes.io/description: "Full access to all Datum Cloud resources in the organization"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: viewer
    - name: organization-admin

    - name: core-admin
      namespace: milo-system
    - name: networking.datumapis.com-admin
      namespace: milo-system
    - name: telemetry.miloapis.com-admin
      namespace: milo-system
