apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: owner
  annotations:
    kubernetes.io/display-name: Owner
    kubernetes.io/description: "Full access to all Datum Cloud resources in the organization"
    taxonomy.miloapis.com/sort-order: "10"
    taxonomy.miloapis.com/product: "Access Everything"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: viewer
      namespace: datum-cloud
    - name: organization-admin
      namespace: datum-cloud
    - name: core-admin
      namespace: milo-system
    - name: networking.datumapis.com-admin
      namespace: milo-system
    - name: telemetry.miloapis.com-admin
      namespace: milo-system
    - name: resourcemanager.miloapis.com-organization-viewer
      namespace: milo-system
    - name: resourcemanager.miloapis.com-project-viewer
      namespace: milo-system
