apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: networking.datumapis.com-gateway-admin
  annotations:
    taxonomy.miloapis.com/sort-order: "72"
    taxonomy.miloapis.com/product: "Configure Networking"
