apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: networking.datumapis.com-viewer
  annotations:
    taxonomy.miloapis.com/sort-order: "80"
    taxonomy.miloapis.com/product: "Configure Networking"
