apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: networking.datumapis.com-admin
  annotations:
    taxonomy.miloapis.com/sort-order: "70"
    taxonomy.miloapis.com/product: "Configure Networking"
