apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: telemetry.miloapis.com-viewer
  annotations:
    taxonomy.miloapis.com/sort-order: "100"
    taxonomy.miloapis.com/product: "Monitor & Observe"
