apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - grant-policies/personal-org-grant-policy.yaml
  - grant-policies/standard-org-grant-policy.yaml
  - validation/organization-update-policy.yaml

patches:
  - path: remove-unified-quota-policy.yaml
    target:
      kind: GrantCreationPolicy
      name: organization-project-quota-policy
