apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - grant-policies/
  - validation/

patches:
  - path: remove-unified-quota-policy.yaml
    target:
      kind: GrantCreationPolicy
      name: organization-project-quota-policy
