apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - grant-policies/organization-project-quota-policy.yaml

patches:
  - path: remove-personal-grant-policy.yaml
    target:
      kind: GrantCreationPolicy
      name: personal-organization-project-quota-policy
  - path: remove-standard-grant-policy.yaml
    target:
      kind: GrantCreationPolicy
      name: standard-organization-project-quota-policy
  - path: remove-personal-org-name-vap.yaml
    target:
      kind: ValidatingAdmissionPolicy
      name: disallow-personal-org-name-change
  - path: remove-personal-org-name-vap-binding.yaml
    target:
      kind: ValidatingAdmissionPolicyBinding
      name: disallow-personal-org-name-change
