apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assignable-organization-roles-viewer-binding
  namespace: datum-cloud
subjects:
  - kind: Group
    name: system:authenticated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assignable-organization-roles-viewer
