---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iam.datumapis.com
  resources:
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resourcemanager.datumapis.com
  resources:
  - organizations
  verbs:
  - create
