apiVersion: iam.datumapis.com/v1alpha1
kind: Service
metadata:
  name: iam.datumapis.com
spec:
  resources:
    - type: iam.datumapis.com/Role
      plural: roles
      singular: role
      permissions:
        - list
        - get
        - create
        - update
        - delete
        - use
        - patch
        - watch
      parentResources:
        - iam.datumapis.com/Service
    - type: iam.datumapis.com/Service
      plural: services
      singular: service
      permissions:
        - list
        - get
        - create
        - update
        - delete
        - patch
        - watch
    - type: iam.datumapis.com/User
      plural: users
      singular: user
      permissions:
        - list
        - get
        - create
        - update
        - delete
        - patch
        - watch
    - type: iam.datumapis.com/Group
      plural: groups
      singular: group
      permissions:
        - list
        - get
        - create
        - update
        - delete
        - patch
        - watch
---
apiVersion: iam.datumapis.com/v1alpha1
kind: Service
metadata:
  name: resourcemanager.datumapis.com
spec:
  resources:
    - type: resourcemanager.datumapis.com/Organization
      plural: organizations
      singular: organization
      permissions:
        - list
        - get
        - create
        - update
        - delete
        - use
        - patch
        - watch
    - type: resourcemanager.datumapis.com/Project
      plural: projects
      singular: project
      permissions:
        - list
        - get
        - create
        - update
        - delete
        - patch
        - watch
