apiVersion: search.miloapis.com/v1alpha1
kind: ResourceIndexPolicy
metadata:
  name: contact-resource-index-policy
spec:
  fields:
  - path: .metadata.name
    searchable: true
  - path: .metadata.annotations["kubernetes.io/display-name"]
    searchable: true
  - path: .metadata.annotations["kubernetes.io/description"]
    searchable: true
  - path: .spec.givenName
    searchable: true
  - path: .spec.familyName
    searchable: true
  - path: .spec.email
    searchable: true
  targetResource:
    group: notification.miloapis.com
    kind: Contact
    version: v1alpha1
