apiVersion: notification.miloapis.com/v1alpha1
kind: EmailTemplate
metadata:
  name: emailtemplates.notification.miloapis.com-userapprovedemailtemplate
spec:
  subject: "🚀 You're in! Your access to Datum is here 🚀"
  htmlBody: |
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html dir="ltr" lang="en">
      <head>
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/logo-datum-light.png" />
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
        <meta name="x-apple-disable-message-reformatting" />
        <title>Your account has been approved</title>
      </head>
      <body
        dir="ltr"
        lang="en"
        style="background-color:rgb(255,255,255);margin-top:0;margin-bottom:0;margin-right:0;margin-left:0">
        <!--$--><!--html--><!--head-->
        <div
          style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0"
          data-skip-in-text="true">
          Your account has been approved
          <div>
             ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿
          </div>
        </div>
        <!--body-->
        <table
          border="0"
          width="100%"
          cellpadding="0"
          cellspacing="0"
          role="presentation"
          align="center">
          <tbody>
            <tr>
              <td
                dir="ltr"
                lang="en"
                style='margin-right:auto;margin-left:auto;margin-bottom:auto;margin-top:auto;background-color:rgb(255,255,255);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:rgb(12,29,49)'>
                <table
                  align="center"
                  width="100%"
                  border="0"
                  cellpadding="0"
                  cellspacing="0"
                  role="presentation"
                  style="max-width:570px;margin-right:auto;margin-left:auto;margin-bottom:80px;margin-top:80px;border-radius:0.5rem;border-style:solid;border-width:1px;border-color:rgb(232,231,228);background-color:rgb(255,255,255)">
                  <tbody>
                    <tr style="width:100%">
                      <td
                        style="padding-bottom:40px;padding-top:40px;padding-right:48px;padding-left:48px">
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <img
                                  alt="Datum"
                                  height="70"
                                  src="https://www.datum.net/download/eng/logo-datum-light.png"
                                  style="display:block;outline:none;border:none;text-decoration:none;margin-right:auto;margin-left:auto;margin-bottom:0;margin-top:0" />
                                <hr
                                  style="width:100%;border:none;border-color:rgb(232,231,228);border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-top:38px;margin-bottom:0;display:block;border-style:solid;border-width:1px" />
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          style="margin-bottom:40px;margin-top:40px">
                          <tbody>
                            <tr>
                              <td>
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:22px;font-weight:500">
                                        Hi
                                        <!-- -->{{.UserName}}<!-- -->,
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:22px;font-weight:400">
                                        Good news, you&#x27;re off the waitlist!
                                        I&#x27;m excited to share what we&#x27;ve
                                        built (so far) with Datum Cloud and get your
                                        feedback. To get started, just login below:
                                      </p>
                                      <a
                                        href="{{.ActionUrl}}"
                                        style="line-height:20px;text-decoration:none;display:block;max-width:100%;mso-padding-alt:0px;border-radius:0.25rem;font-weight:600;text-align:center;text-decoration-line:none;border-style:solid;border-width:1px;background-color:rgb(191,149,149);color:rgb(255,255,255);border-color:rgb(191,149,149);padding-right:24px;padding-left:24px;padding-bottom:14px;padding-top:14px;font-size:16px;margin-top:36px;margin-bottom:32px"
                                        target="_blank"
                                        ><span
                                          ><!--[if mso]><i style="mso-font-width:400%;mso-text-raise:21" hidden>&#8202;&#8202;&#8202;</i><![endif]--></span
                                        ><span
                                          style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:10.5px"
                                          >Start building</span
                                        ><span
                                          ><!--[if mso]><i style="mso-font-width:400%" hidden>&#8202;&#8202;&#8202;&#8203;</i><![endif]--></span
                                        ></a
                                      >
                                      <p
                                        style="font-size:17px;line-height:24px;font-weight:400;margin-top:16px;margin-bottom:16px">
                                        We&#x27;re releasing new features each week
                                        and chatting about issues and opportunities
                                        on<!-- -->
                                        <a
                                          href="https://link.datum.net/discord"
                                          style="color:rgb(191,149,149)!important;text-decoration-line:underline!important"
                                          target="_blank"
                                          >Discord</a
                                        >. Feel free to join me there with any
                                        questions or feedback.
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;font-weight:400;margin-top:22px;margin-bottom:0">
                                        Cheers,<br /><br />Zac Smith<br />Co-founder
                                        &amp; CEO at Datum
                                      </p>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <hr
                                  style="width:100%;border:none;border-color:rgb(232,231,228);border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-bottom:40px;margin-top:0;display:block;border-style:solid;border-width:1px" />
                                <p
                                  style="font-size:14px;line-height:20px;font-weight:400;margin:0;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                  Learn more about how Datum is connecting
                                  infrastructure for AI at<!-- -->
                                  <a
                                    href="https://datum.net"
                                    style="color:rgb(191,149,149);text-decoration-line:underline"
                                    target="_blank"
                                    >datum.net</a
                                  >
                                </p>
                                <p
                                  style="font-size:14px;line-height:20px;margin:0;margin-top:24px;margin-bottom:24px;margin-left:0;margin-right:0">
                                  <a
                                    href="https://www.datum.net/legal/terms"
                                    style="color:rgb(191,149,149);text-decoration-line:underline"
                                    target="_blank"
                                    >Terms of Service</a
                                  >   |   <a
                                    href="https://www.datum.net/legal/privacy"
                                    style="color:rgb(191,149,149);text-decoration-line:underline"
                                    target="_blank"
                                    >Privacy Policy</a
                                  >   |   <a
                                    href="https://www.datum.net/legal/aup"
                                    style="color:rgb(191,149,149);text-decoration-line:underline"
                                    target="_blank"
                                    >Acceptable Use Policy</a
                                  >
                                </p>
                                <p
                                  style="font-size:14px;line-height:20px;margin:0;font-weight:400;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                  Datum Technology Inc. <br />120 Broadway, 26th
                                  Floor <br />New York, NY 10271
                                </p>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
        <!--/$-->
      </body>
    </html>
    

  textBody: |
    ----------------------------------------
    
    Hi {{.UserName}},
    
    Good news, you're off the waitlist! I'm excited to share what we've built (so far) with Datum Cloud and get your feedback. To get started, just login below:
    
    Start building {{.ActionUrl}}
    
    We're releasing new features each week and chatting about issues and opportunities on Discord https://link.datum.net/discord. Feel free to join me there with any questions or feedback.
    
    Cheers,
    
    Zac Smith
    Co-founder & CEO at Datum
    
    ----------------------------------------
    
    Learn more about how Datum is connecting infrastructure for AI at datum.net https://datum.net
    
    Terms of Service https://www.datum.net/legal/terms   |   Privacy Policy https://www.datum.net/legal/privacy   |   Acceptable Use Policy https://www.datum.net/legal/aup
    
    Datum Technology Inc.
    120 Broadway, 26th Floor
    New York, NY 10271

  variables:
  - name: "UserName"
    required: true
    type: "string"
  - name: "ActionUrl"
    required: true
    type: "string"