apiVersion: notification.miloapis.com/v1alpha1
kind: ContactGroupEnrollmentPolicy
metadata:
  name: all-users-enrollment-policy
spec:
  contactGroupRef:
    name: allusers-contact-group-4lqxdp
    namespace: default
  trigger:
    type: ContactCreated
  contactSelector:
    subjectKind: User
