name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: ["published"]

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest

    # Define the services that should be built.
    strategy:
      matrix:
        service:
          - datum-authorization-webhook

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: ghcr.io/datum-cloud/${{ matrix.service }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build ${{ matrix.service }}
      id: push
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        file: cmd/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/datum-cloud/${{ matrix.service }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
